version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    volumes:
      - .:/app

  test:
    build: .
    environment:
      - OPENAI_KEY=mock_openai_key
    command: [ "pytest" ]
